### ISSUE TITLE
[BUG] Random volume name & not in stack

### ISSUE THREAD

**Issue by PedroCisnerosSantana** [appwrite/docker-clamav#4]
When we make an install of appwrite, if we check the volumes we will see one with a random generated name and not in the appwrite stack
![image](https://user-images.githubusercontent.com/37348419/83168539-e9f6c100-a111-11ea-91a5-f7816a98f097.png)

If we look for info of this volume we will see it's related to clamav
![image](https://user-images.githubusercontent.com/37348419/83168616-05fa6280-a112-11ea-8aef-c2f7a51f9efb.png)

**Comment by W4nn4Die** [comment]
@eldadfux seems to be fixed 
![image](https://user-images.githubusercontent.com/37348419/83546380-d6c46680-a500-11ea-9244-685ae4e3c2fe.png)

**Comment by eldadfux** [comment]
Did you do anything?

**Comment by W4nn4Die** [comment]
Hello @eldadfux sorry for the late response, just removed the line you told me and had no problem

**Comment by eldadfux** [comment]
Solved #5 , Thanks @PedroCisnerosSantana !
