### ISSUE TITLE
Convert base image to use alpine instead of ubuntu

### ISSUE THREAD

**Issue by eldadfux** [appwrite/docker-clamav#6]
We are looking for ways to make Appwrite Docker images smaller.

**Comment by SoftCreatR** [comment]
I would take this over. I'm not a Docker expert (started 2 weeks ago to work with it), but i made a good progress so far.

Before (based on ac15834550d1c7f606c02da530ea0b311e52fd32):

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
appwrite/clamav     ubuntu              e050db8f8fae        10 seconds ago      163MB
ubuntu              18.04               c14bccfdea1c        8 days ago          63.2MB
```

After:

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
appwrite/clamav     alpine              b026b81f32d0        11 seconds ago      18MB
alpine              3                   a24bb4013296        3 months ago        5.57MB
```

**Comment by eldadfux** [comment]
Wow, that looks like a huge improvement. I have assigned you the issue.

Feel free to reach out on Discord (https://appwrite.io/discord) if you have any question.

**Comment by devmohit-live** [comment]
Is there any specific version of alpine docker image is required or latest one will do the work?

**Comment by SoftCreatR** [comment]
I'm using the latest one.

I'm already done, converting this. I'll soon create the PR.
